name: lint

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Checkout repository using git
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11.11.0
          cache: true

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - run: pnpm install
      - run: pnpm lint
